export const data = [
  {
    id: '102-69-6423',
    name: 'Ewart',
    age: 32,
    sex: 'M',
    adresses: 'Yelets State University',
  },
  {
    id: '773-53-0652',
    name: 'Burnaby',
    age: 75,
    sex: 'M',
    adresses: 'Universidad Cristiana de las Asambleas de Dios',
  },
  {
    id: '601-21-8448',
    name: 'Ronda',
    age: 92,
    sex: 'F',
    adresses: 'Universidade Lusíada de Angola',
  },
  {
    id: '393-08-3152',
    name: 'Raphaela',
    age: 28,
    sex: 'F',
    adresses: 'Triton College',
  },
  {
    id: '779-99-5869',
    name: 'Raff',
    age: 36,
    sex: 'M',
    adresses: 'University of Ibadan',
  },
  {
    id: '443-71-9927',
    name: 'Nickey',
    age: 72,
    sex: 'M',
    adresses: 'Kobe University of Mercantile Marine',
  },
  {
    id: '744-15-0677',
    name: 'Gardy',
    age: 26,
    sex: 'M',
    adresses: 'Fachhochschule Mannheim, Hochschule für Technik und Gestaltung',
  },
  {
    id: '562-33-3687',
    name: 'Zebulen',
    age: 59,
    sex: 'M',
    adresses: 'Hartford Graduate Center (Rensselaer at Hartford)',
  },
  {
    id: '508-09-3691',
    name: 'Kamillah',
    age: 64,
    sex: 'F',
    adresses: 'Université de Sidi-Bel-Abbès (Djillali Liabès)',
  },
  {
    id: '258-16-6767',
    name: 'Orlando',
    age: 59,
    sex: 'M',
    adresses: ' Technological University (Yangon)',
  },
];
